version: 0.2

env:
  variables:
    ECR_REPO_NAME: my-angular-app # static, available everywhere

  exported-variables:
    - ECR_URI
    - REPO_URI
    - IMAGE_TAG

phases:
  pre_build:
  commands:
    - set -euxo pipefail
    - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
    - REGION="${AWS_REGION:-${AWS_DEFAULT_REGION}}"
    - export ECR_URI="${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"
    - export REPO_URI="${ECR_URI}/${ECR_REPO_NAME}"
    - export IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
    - aws ecr get-login-password --region "$REGION" | docker login -u AWS --password-stdin "$ECR_URI"

  build:
    commands:
      - docker build -t "${ECR_REPO_NAME}:${IMAGE_TAG}" .

  post_build:
    commands:
      - set -euxo pipefail
      - docker tag "${ECR_REPO_NAME}:${IMAGE_TAG}" "${REPO_URI}:${IMAGE_TAG}"
      - docker push "${REPO_URI}:${IMAGE_TAG}"
      # Generate image definition file for ECS.
      - printf '[{"name":"my-angular-app","imageUri":"%s"}]' "${REPO_URI}:${IMAGE_TAG}" > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
  - imagedefinitions.json