version: 0.2
environment:
  variables:
    AWS_REGION: "eu-west-1"
    ECR_REPO_NAME: "my-angular-app"
phases:
  pre_build:
    commands:
    # Log in to Docker Hub
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin

    #ECR login
      - ECR_MAIN_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - aws ecr get-login-password --region ${AWS_REGION} | docker login -u AWS --password-stdin ${ECR_MAIN_URI}
      - REPOSITORY_URI="${ECR_MAIN_URI}/${ECR_REPO_NAME}:latest"
  build:
    commands:
      - docker build -t ${ECR_REPO_NAME}:latest .

  post_build:
    commands:
      - docker tag ${ECR_REPO_NAME}:latest ${REPOSITORY_URI}
      - docker push ${REPOSITORY_URI}